import { CompleteCase } from './types';

export const GRADES = [
  '19', '22', '24', '29', '32', '36', '41', '44', '48', '52', '54', '56',
  'JUSA C', 'JUSA B', 'JUSA A', 'TURUS III', 'TURUS II', 'TURUS I'
];

export const MINISTRIES = [
  'JPM - Jabatan Perdana Menteri',
  'KKM - Kementerian Kesihatan Malaysia',
  'KPM - Kementerian Pendidikan Malaysia',
  'KDN - Kementerian Dalam Negeri',
  'JPA - Jabatan Perkhidmatan Awam',
  'MOF - Kementerian Kewangan',
  'MINDEF - Kementerian Pertahanan',
  'MOSTI - Kementerian Sains, Teknologi dan Inovasi',
  'KLN - Kementerian Luar Negeri',
  'MITI - Kementerian Pelaburan, Perdagangan dan Industri',
  'KKR - Kementerian Kerja Raya',
  'MOT - Kementerian Pengangkutan',
  'KBS - Kementerian Belia dan Sukan',
  'KSM - Kementerian Sumber Manusia',
  'KPWKM - Kementerian Pembangunan Wanita, Keluarga dan Masyarakat',
  'KPT - Kementerian Pendidikan Tinggi',
  'KPKT - Kementerian Perumahan dan Kerajaan Tempatan',
  'MAFS - Kementerian Pertanian dan Keterjaminan Makanan',
  'NRES - Kementerian Sumber Asli dan Kelestarian Alam',
  'PETRA - Kementerian Peralihan Tenaga dan Transformasi Air',
  'KEM. DIGITAL - Kementerian Digital',
  'KEM. KOMUNIKASI - Kementerian Komunikasi',
  'SPRM - Suruhanjaya Pencegahan Rasuah Malaysia',
  'SPA - Suruhanjaya Perkhidmatan Awam',
  'SPP - Suruhanjaya Perkhidmatan Pendidikan',
  'LAIN-LAIN'
];

export const STATES = [
  'W.P. KUALA LUMPUR',
  'W.P. PUTRAJAYA',
  'W.P. LABUAN',
  'JOHOR',
  'KEDAH',
  'KELANTAN',
  'MELAKA',
  'NEGERI SEMBILAN',
  'PAHANG',
  'PERAK',
  'PERLIS',
  'PULAU PINANG',
  'SABAH',
  'SARAWAK',
  'SELANGOR',
  'TERENGGANU'
];

export const KAUM = [
  'MELAYU',
  'CINA',
  'INDIA',
  'BUMIPUTERA SABAH',
  'BUMIPUTERA SARAWAK',
  'ORANG ASLI',
  'SIKH',
  'LAIN-LAIN KAUM'
];

export const STATUS_JAWATAN = [
  'HAKIKI',
  'MEMANGKU',
  'KUP (Khas Untuk Penyandang)',
  'KONTRAK',
  'LAIN-LAIN'
];

export const PUNCA_KES = [
  'JABATAN',
  'JK SIASATAN',
  'MOF',
  'LPBI',
  'LSPRM',
  'AUDIT',
  'NAZIRAN',
  'INSOLVENSI',
  'ADUAN',
  'LKAN',
  'MAHKAMAH (SPRM)'
];

export const JENIS_KESALAHAN = [
  'Kewangan/ Perolehan',
  'Tidak Hadir Bertugas',
  'Tidak Berada Di Tempat Bertugas',
  'Tidak Ketik Kad Perakam Waktu',
  'Gagal Lapor Diri',
  'Hadir Lewat Ke Pejabat/ Pulang Awal Dari Pejabat',
  'Mengambil Cuti Rehat Melebihi Kelayakan',
  'Pecah Kecil Perolehan',
  'Gangguan Seksual',
  'Salah Guna Kuasa',
  'Bankrap',
  'Gagal Menyelia',
  'Keluar Negara Tanpa Kebenaran',
  'Pemalsuan Dokumen/ Maklumat',
  'Kecuaian Perubatan',
  'Menggunakan Pengaruh Luar',
  'Pekerjaan Luar Tanpa Kebenaran',
  'Terlibat Dalam Politik',
  'Tatacara Berpakaian',
  'Penyalahgunaan Dadah',
  'Penerimaan Hadiah',
  'Penerimaan Keraian',
  'Gagal Isytihar Harta',
  'Keterhutangan Serius',
  'Meminjamkan Wang Dengan Faedah',
  'Keterlibatan Dalam Pasaran Niaga Hadapan',
  'Mengelola Cabutan Hadiah Dan Loteri Bukan Tujuan Untuk Kebajikan',
  'COVID-19',
  'Penerbitan Berdasarkan Maklumat Rasmi Terperingkat',
  'Pernyataan Awam Tanpa Kebenaran',
  'Penyuntingan Dan Penerbitan Tanpa Kebenaran',
  'LKAN',
  'Lain-Lain Kesalahan',
  'Surcaj',
  'Mencemar Nama Perkhidmatan Awam',
  'Ingkar Perintah',
  'Tuntutan Palsu',
  'Salah Guna Kenderaan Jabatan',
  'Cuai Dalam Melaksanakan Tugas',
  'Tidak Bertanggungjawab',
  'Tidak Jujur Atau Tidak Amanah',
  'Kurang Cekap Atau Kurang Berusaha',
  'Mengeluarkan Sijil Cuti Sakit Palsu',
  'Kemuka Sijil Cuti Sakit Palsu',
  'Kesalahan Berkaitan Penglibatan Dalam Aktiviti Politik',
  'Tidak Melengkapkan Buku Rekod Mengajar',
  'Berkaitan Jenayah SPRM',
  'Berkaitan Jenayah - Seksual Terhadap Kanak-Kanak'
];

export const KEPUTUSAN_PERTUDUHAN = [
  'Bebas',
  'Amaran',
  'Denda (1 hari)',
  'Denda (2 hari)',
  'Denda (3 hari)',
  'Denda (4 hari)',
  'Denda (5 hari)',
  'Denda (6 hari)',
  'Denda (7 hari)',
  'Lucut Hak Emolumen',
  'Tangguh Pergerakan Gaji (3 bulan)',
  'Tangguh Pergerakan Gaji (6 bulan)',
  'Tangguh Pergerakan Gaji (9/12 bulan)',
  'Turun Gaji 1 pergerakan (12 bulan)',
  'Turun Gaji 1 pergerakan (24 bulan)',
  'Turun Gaji 2 pergerakan (12 bulan)',
  'Turun Pangkat',
  'Buang Kerja',
  'Surcaj (Bertanggungan)',
  'Surcaj (Tidak Bertanggungan)',
  'Dalam Penelitian SPA/ SPP',
  'Letak Jawatan (Tutup Kes)',
  'Bersara (Tutup Kes)',
  'Tarik Kes (Tutup Kes)',
  'Perintah Tahan Kerja P43',
  'Perintah Tahan Kerja P44',
  'Perintah Gantung Kerja P45'
];

export const INITIAL_CASES: CompleteCase[] = [
  {
    metadata: {
      BIL: 1,
      NO_RUJ_FAIL_JPA: 'JPA.C.P.100-2/4/12(15)',
      BIL_IKUT_SUSUNAN_PAPER: '2026/04/01',
      URL_LINK_GD: 'https://drive.google.com/drive/folders/1aBcDeFgHiJkLmNoPqRsTuVwXyZ',
      URL_LINK_LSPRM_LPBI_ADUAN: 'https://aduan.sprm.gov.my/case/sprm-2026-99182',
      URL_LINK_PP: 'https://drive.google.com/file/d/1XyZ_kertas_makluman/view',
      URL_LINK_SP: 'https://drive.google.com/file/d/1XyZ_surat_pertuduhan/view',
      URL_LINK_PH: 'https://drive.google.com/file/d/1XyZ_surat_hukuman/view',
      URL_LINK_SK: 'https://drive.google.com/file/d/1XyZ_surat_keputusan/view'
    },
    officer: {
      NAMA: 'Ahmad bin Sulaiman',
      NO_KP: '820412145533',
      TARIKH_LAHIR: '12-APR-1982',
      PILIHAN_UMUR_PERSARAAN: 60,
      TARIKH_BERSARA: '12-APR-2042',
      JANTINA: 'L',
      KAUM: 'MELAYU',
      JAWATAN: 'Pegawai Teknologi Maklumat',
      SKIM: 'F - Teknologi Maklumat dan Komunikasi',
      GRED: '48',
      STATUS_JAWATAN: 'HAKIKI',
      TEMPAT_BERTUGAS: 'Bahagian Pengurusan Maklumat, JPA Putrajaya',
      NEGERI: 'W.P. PUTRAJAYA',
      KEMENTERIAN: 'JPA - Jabatan Perkhidmatan Awam'
    },
    details: {
      KESALAHAN_ALL: 'Pegawai didapati tidak hadir bertugas selama 14 hari berturut-turut bermula dari 2 Mac 2026 hingga 15 Mac 2026 tanpa sebarang cuti atau kebenaran terlebih dahulu, serta gagal mengemukakan sijil sakit yang sah.',
      JENIS_KESALAHAN: ['Tidak Hadir Bertugas', 'Ingkar Perintah'],
      RINGKASAN_KESALAHAN: 'Ketidakhadiran bertugas tanpa cuti/kebenaran berturut-turut selama 14 hari.',
      ULASAN_URUS_SETIA: 'Urus Setia mendapati pegawai tidak mempunyai rekod kesalahan lampau. Walau bagaimanapun, tindakan tatatertib wajar diteruskan di bawah Peraturan 23 Peraturan-Peraturan Pegawai Awam (Kelakuan dan Tatatertib) 1993.',
      PUNCA_KES: 'JABATAN',
      CATATAN: 'Pegawai memberikan penjelasan lewat selepas surat tunjuk sebab dikeluarkan.',
      LINK_PINDA_CATATAN: 'https://drive.google.com/file/d/1catatan_pindahan_ahmad/view',
      TARIKH_KEMUKA_PINDA_KERTAS: '2026-05-10T09:00:00Z'
    },
    workflow: {
      STATUS_KATEGORI: 'B05c PP - PP Edaran Diluluskan PBK - Urusetia',
      STATUS_KATEGORI_UTAMA: 'Penentuan Pengerusi',
      STATUS_KEMASKINI_KES_DI_HRMIS: 'SP Updated',
      PEGAWAI_KES: '02) KPP OA1 - EZLY (OA)',
      SME: 'YUS YULANDY (OA)',
      PEGAWAI_PENYEMAK: '01) TPB - ROSMASHILAH (OA)',
      TAHUN_TERIMA: 2026,
      TARIKH_TERIMA_PERAKUAN: '2026-03-20',
      TAHUN_KPI: 2026,
      TARIKH_SERAHAN_KEPADA_PEGAWAI_KES: '2026-03-22',
      TARIKH_DOKUMEN_LENGKAP: '2026-03-28',
      TARIKH_LULUS_PP: '2026-04-15',
      TARIKH_KEMUKA_PP_KE_KPP: '2026-04-02',
      TARIKH_KEMUKA_PP_KE_TPB: '2026-04-05',
      TARIKH_KEMUKA_PP_KE_TPBK: '2026-04-08',
      STATUS_DRAF_PP_DAN_SLAID_MKSN: 'Selesai Edaran',
      TARIKH_MESY_JK2T_MKSN: '2026-04-12',
      TARIKH_LULUS_PP_OLEH_JK2T: '2026-04-15',
      BIL_MESY_MKSN_MPP: 'Bil 2/2026',
      TARIKH_HANTAR_PP_KE_KSN: '2026-04-20',
      TARIKH_PENENTUAN_PENGERUSI: '2026-04-25',
      PENENTUAN: 'P36 - Wujud Kesalahan',
      TARIKH_KEMUKA_SP_KE_URUSETIA: '2026-05-02',
      TARIKH_KEMUKA_DRAF_SP_KE_PUU: '2026-05-05',
      TARIKH_KEMUKA_SP_KE_TPB: '2026-05-10',
      TARIKH_SP: '2026-05-15',
      TARIKH_SURAT_REP: '2026-05-16',
      TARIKH_TERIMA_SURAT_REP: '2026-05-30',
      TARIKH_TERIMA_SURAT_REP_OLEH_PEGAWAI_KES: '2026-06-02'
    }
  },
  {
    metadata: {
      BIL: 2,
      NO_RUJ_FAIL_JPA: 'JPA.C.P.100-2/4/13(08)',
      BIL_IKUT_SUSUNAN_PAPER: '2026/05/12',
      URL_LINK_GD: 'https://drive.google.com/drive/folders/2dEfGhIjKlMnOpQrStUvWxYzAbC',
      URL_LINK_LSPRM_LPBI_ADUAN: '',
      URL_LINK_PP: 'https://drive.google.com/file/d/2AbCd_kertas_makluman/view',
      URL_LINK_SP: '',
      URL_LINK_PH: '',
      URL_LINK_SK: ''
    },
    officer: {
      NAMA: 'Fatimah binti Md Nor',
      NO_KP: '780915036688',
      TARIKH_LAHIR: '15-SEP-1978',
      PILIHAN_UMUR_PERSARAAN: 58,
      TARIKH_BERSARA: '15-SEP-2036',
      JANTINA: 'P',
      KAUM: 'MELAYU',
      JAWATAN: 'Pegawai Tadbir dan Diplomatik',
      SKIM: 'M - Pentadbiran dan Sokongan',
      GRED: '52',
      STATUS_JAWATAN: 'HAKIKI',
      TEMPAT_BERTUGAS: 'Kementerian Pendidikan Malaysia, Putrajaya',
      NEGERI: 'W.P. PUTRAJAYA',
      KEMENTERIAN: 'KPM - Kementerian Pendidikan Malaysia'
    },
    details: {
      KESALAHAN_ALL: 'Pegawai disyaki menggunakan kedudukan rasminya untuk menyokong pelantikan syarikat milik adik kandungnya bagi pembekalan alat tulis di jabatan.',
      JENIS_KESALAHAN: ['Salah Guna Kuasa', 'Kewangan/ Perolehan'],
      RINGKASAN_KESALAHAN: 'Conflict of Interest dalam perolehan pembekalan alat tulis.',
      ULASAN_URUS_SETIA: 'Syor kes dibawa ke Lembaga Tatatertib Kumpulan Pengurusan (No. 1) untuk tindakan di bawah Peraturan 4(2)(d) iaitu membelakangkan kewajipan kepada awam demi kepentingan peribadi.',
      PUNCA_KES: 'ADUAN',
      CATATAN: 'Siasatan dalaman selesai, kes diklasifikasikan sebagai prima facie.',
      LINK_PINDA_CATATAN: '',
      TARIKH_KEMUKA_PINDA_KERTAS: ''
    },
    workflow: {
      STATUS_KATEGORI: 'B01 PP - Penyediaan PP - Pegawai Kes',
      STATUS_KATEGORI_UTAMA: 'Klarifikasi & Perincian Kesalahan',
      STATUS_KEMASKINI_KES_DI_HRMIS: 'Incomplete',
      PEGAWAI_KES: '04) KPP OA3 - FAEZAH (OA)',
      SME: 'RATINA (OA)',
      PEGAWAI_PENYEMAK: '01) TPB - ROSMASHILAH (OA)',
      TAHUN_TERIMA: 2026,
      TARIKH_TERIMA_PERAKUAN: '2026-05-10',
      TAHUN_KPI: 2026,
      TARIKH_SERAHAN_KEPADA_PEGAWAI_KES: '2026-05-12',
      TARIKH_DOKUMEN_LENGKAP: '2026-05-20',
      TARIKH_KEMUKA_PP_KE_KPP: '2026-06-01',
      STATUS_DRAF_PP_DAN_SLAID_MKSN: 'Penyediaan Draf',
      TARIKH_MESY_JK2T_MKSN: '',
      TARIKH_LULUS_PP_OLEH_JK2T: '',
      BIL_MESY_MKSN_MPP: '',
      TARIKH_HANTAR_PP_KE_KSN: '',
      TARIKH_PENENTUAN_PENGERUSI: '',
      PENENTUAN: ''
    }
  }
];
